# Generated by Django 3.0 on 2019-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cusips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip_code', models.CharField(max_length=9)),
                ('ticker', models.CharField(max_length=20)),
                ('entity_name', models.CharField(max_length=100)),
                ('market_sector', models.CharField(max_length=15)),
                ('security_type', models.CharField(max_length=15)),
                ('exchange_code', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(verbose_name='cusip_date')),
            ],
        ),
    ]
