# Generated by Django 3.0 on 2019-12-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusips',
            name='cusip_code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
