# Generated by Django 3.0 on 2019-12-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusips', '0002_auto_20191213_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusips',
            name='entity_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cusips',
            name='exchange_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cusips',
            name='ticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
